package com.dorosoft.erp.table.application;

public enum TableErrorCode {
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_KEY_CONFLICT,
    INVALID_TABLE_NUMBER,
    INVALID_DISPLAY_NAME,
    INVALID_SEAT_CAPACITY,
    TABLE_NOT_FOUND,
    TABLE_NUMBER_DUPLICATED,
    QR_ACCESS_DENIED,
    QR_CREDENTIAL_ALREADY_ACTIVE,
    QR_HOST_FORBIDDEN,
    QR_RATE_LIMITED,
    TABLE_SESSION_ALREADY_OPEN,
    TABLE_SESSION_ALREADY_CLOSED,
    TABLE_SESSION_CLOSE_BLOCKED,
    TABLE_SESSION_NOT_FOUND,
    TABLE_SESSION_NOT_AVAILABLE,
    PRECONDITION_FAILED,
    PRECONDITION_REQUIRED
}
