package com.dorosoft.erp.table.application;

public enum TableErrorCode {
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_KEY_CONFLICT,
    INVALID_TABLE_NUMBER,
    INVALID_DISPLAY_NAME,
    INVALID_SEAT_CAPACITY,
    TABLE_NOT_FOUND,
    TABLE_NUMBER_DUPLICATED,
    QR_CREDENTIAL_ALREADY_ACTIVE,
    PRECONDITION_FAILED,
    PRECONDITION_REQUIRED
}
