package com.dorosoft.erp.store.domain.feature;

public enum NotificationEventCode {
    WAITING_REGISTERED,
    WAITING_CALLED,
    RESERVATION_REQUESTED,
    RESERVATION_APPROVED,
    RESERVATION_REJECTED,
    RESERVATION_CHANGED,
    RESERVATION_CHANGE_REJECTED,
    RESERVATION_CANCELLED,
    RESERVATION_REMINDER,
    PICKUP_ORDER_RECEIVED,
    PICKUP_READY,
    PAYMENT_COMPLETED,
    PAYMENT_CANCELLED
}
