package com.dorosoft.erp.audit.application.api;

public enum AuditErrorCode {
    AUDIT_EVENT_CONFLICT,
    AUDIT_REASON_REQUIRED,
    AUDIT_SCHEMA_UNSUPPORTED,
    AUDIT_SENSITIVE_VALUE_REJECTED,
    AUDIT_VALUE_TOO_LARGE,
    AUDIT_UNAVAILABLE,
    PRIVACY_ACCESS_LOG_UNAVAILABLE,
    INVALID_AUDIT_FILTER,
    INVALID_PERIOD,
    INVALID_CURSOR,
    INVALID_LIMIT
}
